### ISSUE TITLE
Handle multiple Steam libraries

### ISSUE THREAD

**Issue by Siilwyn** [AyriaPublic/AyriaDesktop#2]
User could have installed Steam games on multiple locations currently the app only looks into the `steamapps` directory inside the directory Steam is located.

**Comment by bheart** [comment]
Obvious and easiest choice here is to simply let the user manage a separate list of Steam libraries, but we could try our hand at parsing Steam's settings. Looks like what we're after is in `Steam/config/config.vdf`. The second Steam library (i.e. the not the one stored in the Windows Registry under `SteamPath`) is the `"BaseInstallFolder_1"` entry, the third is `"BaseInstallFolder_2"` and so on.

**Comment by bheart** [comment]
Hmm, looks as if there's also `Steam/steamapps/libraryfolders.vdf`, which appears to be listing the exact same thing, except much cleaner. I'll probably re-write it to use that one instead.
