### ISSUE TITLE
Cache listed games

### ISSUE THREAD

**Issue by Siilwyn** [AyriaPublic/AyriaDesktop#7]
The fetched information about installed games should be cached.

**Comment by Convery** [comment]
Should we block while scanning if there's no cache or have some icon indicating that it's processing and the gameslist is not final? If there's a cache, should we run a low-priority thread in the background daily to update it or have the user issue a scan?

**Comment by Siilwyn** [comment]
Yes an indicator is necessary and I would say let's scan for games on startup? But let's not block the while view while doing that.
