### ISSUE TITLE
Move all var to const/let

### ISSUE THREAD

**Issue by xCausxn** [AyriaPublic/AyriaDesktop#9]
As this is a ES6 environment and const is already being used, all declaration of ```var``` should be moved to either ```const``` or ```let```

Example
https://github.com/AyriaPublic/AyriaDesktop/blob/master/src/list-steamapps/list-steamapps.js#L68

**Comment by Siilwyn** [comment]
Thanks for your feedback @xCausxn, I've [enforced this with ESLint](https://github.com/AyriaPublic/AyriaDesktop/pull/12) to make it clear.
